[MESSAGES CONTROL]

# Enable the message(s) with id(s) separated by a comma.
# enable=

# Disable the message(s) with id(s) separated by a comma.
disable=
    C0301,  # Line too long
    R0912,  # Too many branches
    R0914,  # Too many local variables
    R0915,  # Too many statements
    W0603,  # Using the global statement
    W0703   # Catching too general exception Exception
