name: Python Pull Request (Src Only)

on:
  pull_request:
    branches: [ main ] # 또는 기본 브랜치 이름

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        pip install flake8
        # 필요하다면 flake8 설정 추가 (예: --max-line-length=120)
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Static Analysis with Pylint
      run: |
        pip install pylint
        # 필요하다면 pylint 설정 파일 추가 (.pylintrc)
        find src/ -name "*.py" -print0 | xargs -0 pylint
    - name: Test with pytest
      run: |
        pip install pytest
        pytest src/ # 또는 테스트 파일이 src 내부에 없다면 해당 경로 지정
